### ISSUE TITLE
can't login after successful installation (on vbox)

### ISSUE THREAD

**Issue by Unixware** [outpaddling/desktop-installer#10]
tested on vbox - maybe that script is not compatible with this? 

XDM displayed ok shortly after boot , but when I am entering my credentials (no matter if root or the user -> they both can login via console) goes back to the XDM.

**Comment by outpaddling** [comment]
It should work fine under vbox.

Which desktop environment are you using?

Also see [https://github.com/outpaddling/desktop-installer/issues/8](https://github.com/outpaddling/desktop-installer/issues/8).

**Comment by Unixware** [comment]
thanks , its icewm and the "test" desktop during the setup opened without any issue.
I ve checked the #8 , not that related to my issue, I do have the XDM , and I start the WM via startx when I login from console login. I may ditch the XDM at all no big deal...

**Comment by outpaddling** [comment]
Try commenting out the sysctl line in /usr/local/etc/xsession.desktop-installer.
Looks like the VBoxClient --display option has been deprecated.
This should allow the WM to start from XDM, but resizing the VBox window probably won't work.

**Comment by outpaddling** [comment]
Actually try replacing VBoxClient --display with VBoxClient --vmsvga.  With this my ICEWM desktop resizes successfully.

**Comment by Unixware** [comment]
ah this works! thanks!

**Comment by outpaddling** [comment]
Good to hear.  Committed 0.7.2.1 to ports with this fix.

**Comment by grahamperrin** [comment]
> vmsvga

If guest additions are installed, you should probably refrain from using VMSVGA.

**Comment by outpaddling** [comment]
Interesting.  Seems to work fine, but I'll investigate further.

**Comment by grahamperrin** [comment]
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=254266#c7

**Comment by outpaddling** [comment]
Thanks - note that what we're referring to here is running "VBoxClient --vmsvga" from Xsession to enable resizing with the VBoxVGA or VBoxSVGA devices, not selecting the VMSVGA device in the VM settings.  Interestingly this seems to work fine with VBoxVGA, though VBoxSVGA is probably a better choice based on the PR discussion.  Desktop-installer currently only does this with the basic window managers currently supported; ICEWM, FluxBox, WindowMaker, all of which passed basic resize testing using VBoxVGA.  This is not necessary for desktop environments such as XFCE, KDE, etc.

**Comment by Unixware** [comment]
Thanks for the work! Looks like FBSD's bug (vbox drivers) as without the XDM the icewm starts (from the console I mean)

**Comment by grahamperrin** [comment]
https://github.com/outpaddling/desktop-installer/issues/10#issuecomment-841691915

Thanks, 

> … "VBoxClient --vmsvga" from Xsession to enable resizing with the VBoxVGA or VBoxSVGA devices …

sorry for overlooking the context. 

(I need to familiarise myself with `desktop-installer` capabilities.)
