### ISSUE TITLE
KDE 5 installation has a blinking and unusable cursor

### ISSUE THREAD

**Issue by yzgyyang** [outpaddling/desktop-installer#19]
Hi!

After a fresh installation of KDE5, the mouse cursor ended up blinking and disappearing and is unusable.

https://user-images.githubusercontent.com/16748524/121646714-97115280-ca63-11eb-955e-f1689bed3076.mp4

Not sure if it is the problem of the script though ;)

**Comment by outpaddling** [comment]
Does it do this with both software and hardware cursor?

```
FreeBSD coral.acadix  bacon ~ 1001: cat /etc/X11/xorg.conf.d/20-swcursor.conf 
Section "Device"
    Identifier "Device0"
    Option "SWCursor" "on"
EndSection
```

**Comment by outpaddling** [comment]
Closing as it does not seem to be desktop-installer related.  Feel free to reopen if you discover evidence that it is.
