### ISSUE TITLE
Desktop-installer halts with errors on repeated runs

### ISSUE THREAD

**Issue by brucelilly** [outpaddling/desktop-installer#2]
Typically, it halts after "error code 70" on attempts to [re]install exfat support etc.  This happens if desktop-installer is run to install additional desktop environments (e.g. for redundancy, to accommodate multiple users with different preferences, change-of-mind, etc.).

Patch:
########### begin patch ##################
*** /usr/local/sbin/desktop-installer.orig      Fri Dec  4 19:59:10 2020
--- /usr/local/sbin/desktop-installer   Sat Dec 12 22:42:09 2020
***************
*** 1122,1128 ****
      # mplayer plugin has no package
      if ! auto-package-installed mplayerplug-in; then
        cd $PORTSDIR/www/mplayer-plugin
!       make -DBATCH install
      fi
  }
  
--- 1122,1128 ----
      # mplayer plugin has no package
      if ! auto-package-installed mplayerplug-in; then
        cd $PORTSDIR/www/mplayer-plugin
!       make -DBATCH deinstall clean reinstall
      fi
  }
  
***************
*** 1135,1144 ****
  {
      pkg install -y libtool automake help2man mp4v2 gmake
      if ! auto-package-installed audio/faac; then
!       (cd $PORTSDIR/audio/faac && make -DBATCH clean install)
      fi
      if ! auto-package-installed audio/lame; then
!       (cd $PORTSDIR/audio/lame && make -DBATCH clean install)
      fi
  }
  
--- 1135,1144 ----
  {
      pkg install -y libtool automake help2man mp4v2 gmake
      if ! auto-package-installed audio/faac; then
!       (cd $PORTSDIR/audio/faac && make -DBATCH deinstall clean reinstall)
      fi
      if ! auto-package-installed audio/lame; then
!       (cd $PORTSDIR/audio/lame && make -DBATCH deinstall clean reinstall)
      fi
  }
  
*** /usr/local/sbin/auto-fusefs-install.orig    Fri Dec  4 05:41:20 2020
--- /usr/local/sbin/auto-fusefs-install Sat Dec 12 22:43:19 2020
***************
*** 6,15 ****
      pkg install -y pkgconf zenity autoconf automake libublio gettext-tools \
        texinfo fusefs-libs
      if ! auto-package-installed sysutils/fusefs-exfat; then
!       (cd $PORTSDIR/sysutils/fusefs-exfat && unset BATCH && make install clean)
      fi
      if ! auto-package-installed sysutils/exfat-utils; then
!       (cd $PORTSDIR/sysutils/exfat-utils && unset BATCH && make install clean)
      fi
      pkg install -y fusefs-ntfs fusefs-ext2 \
        fusefs-hfsfuse fusefs-simple-mtpfs
--- 6,15 ----
      pkg install -y pkgconf zenity autoconf automake libublio gettext-tools \
        texinfo fusefs-libs
      if ! auto-package-installed sysutils/fusefs-exfat; then
!       (cd $PORTSDIR/sysutils/fusefs-exfat && unset BATCH && make deinstall clean reinstall)
      fi
      if ! auto-package-installed sysutils/exfat-utils; then
!       (cd $PORTSDIR/sysutils/exfat-utils && unset BATCH && make deinstall clean reinstall)
      fi
      pkg install -y fusefs-ntfs fusefs-ext2 \
        fusefs-hfsfuse fusefs-simple-mtpfs
############ end patch ###############

That repeats the process for every run, which is a minor nuisance; it's probably necessary, though, to handle things like interim patches and updates.

**Comment by outpaddling** [comment]
Thanks for the feedback and patches.

Can you try the latest from my WIP collection?

[https://github.com/outpaddling/freebsd-ports-wip](https://github.com/outpaddling/freebsd-ports-wip)

**Comment by brucelilly** [comment]
On Sun, Dec 13, 2020 at 5:26 PM Jason Bacon <notifications@github.com>
wrote:

> Can you try the latest from my WIP collection?
>
That version of desktop-installer exits with status 2 after
emitting devfs-related stuff, but before "Installation of Xorg".
Output from the last user input to script termination follows.

Scan for additional sound devices? (y/[n])
/proc is already mounted.
14 Dec 10:21:38 ntpdate[21622]: adjust time server 137.190.2.4 offset
+0.268829 sec
ntpd already running.
If you need the service restarted, you must do it manually.
nfs_client already running.
If you need the service restarted, you must do it manually.
rpc_statd already running.
If you need the service restarted, you must do it manually.
rpc_lockd already running.
If you need the service restarted, you must do it manually.
rpc_statd already running.
If you need the service restarted, you must do it manually.
rpc_lockd already running.
If you need the service restarted, you must do it manually.
Stopping lockd.
Waiting for PIDS: 16438.
Starting lockd.
Stopping statd.
Waiting for PIDS: 16461.
Starting statd.
autofs already enabled.
automountd already running?  (pid=1881).
autounmountd already running?  (pid=1887).

NFS shares on the local network should be accessible via autofs under
/net/<server-hostname>/.

devd already running.
If you need the service restarted, you must do it manually.
Entry already exists in devfs.rules for ugen.
Entry already exists in devfs.rules for cuaU.
Entry already exists in devfs.rules for uhid.
Entry already exists in devfs.rules for usbctl.
Entry already exists in devfs.rules for usb/.
Entry already exists in devfs.rules for video.
Entry already exists in devfs.conf for cuad0.
Entry already exists in devfs.conf for cuad1.
Entry already exists in devfs.conf for cuau0.
Entry already exists in devfs.conf for cuau1.
devd already running.
If you need the service restarted, you must do it manually.
Entry already exists in devfs.rules for ng_ubt.
devd already running.
If you need the service restarted, you must do it manually.
Entry already exists in devfs.rules for cd.
Entry already exists in devfs.rules for da.
Entry already exists in devfs.rules for pass.
Entry already exists in devfs.rules for xpt.
Entry already exists in devfs.conf for cd0.
Entry already exists in devfs.conf for cd1.
Entry already exists in devfs.conf for fd0.
Entry already exists in devfs.conf for fd1.
vfs.usermount: 1 -> 1
vfs.usermount: 1 -> 1

**Comment by outpaddling** [comment]
I can't reproduce this issue.  Can you try it with the following patch and post the tail of the output?
Thanks.
```
--- /usr/local/sbin/desktop-installer	2020-12-14 16:32:34.090081000 -0600
+++ desktop-installer	2020-12-14 16:39:33.311193000 -0600
@@ -2579,6 +2579,7 @@
     chmod 750 /dev/usb
 fi
 external_drive_config
+set -x
 
 # Ask the questions before beginning so the installation can
 # run unattended
```

**Comment by outpaddling** [comment]
Cannot reproduce.  Please reopen if the problem continues and you can provide more information.
