### ISSUE TITLE
Virtualbox Guest Additions installed but not enabled by default

### ISSUE THREAD

**Issue by yzgyyang** [outpaddling/desktop-installer#20]
```
vboxguest_enable="YES"
vboxservice_enable="YES"
```
Even better if we can just start the service right after the installation ;)

**Comment by outpaddling** [comment]
It does start them immediately:

```
install_packages emulators/virtualbox-ose-additions
auto-enable-service vboxguest desktop-installer
auto-enable-service vboxservice desktop-installer
```
Have a look at the auto-enable-service script.
Mouse integration always works for me during X11 testing, so I know it's running.  What are you seeing to imply that it's not?

**Comment by yzgyyang** [comment]
I don't seem to be able to reproduce it either, so closing it for now... Sorry for the noise!
