### ISSUE TITLE
Lumina

### ISSUE THREAD

**Issue by rracb** [outpaddling/desktop-installer#22]
With respect to your wonderful FreeBSD desktop-installer script, please be advised that Lumina is no longer supported and will sunset (EOL) March 1, 2022.

<https://project-trident.org/post/2021-10-29_sunset/>

Sadly...

AKC

PS - the contact form on your website doesn't work. Returns:

Not Found
The requested URL was not found on this server.

**Comment by outpaddling** [comment]
The sunset link is in regard to Trident OS, which is a Linux distribution.  Lumina desktop is one component of it and a separate project.  There has been minimal activity in the project, but it is not dead:

https://lumina-desktop.org/
https://github.com/lumina-desktop/lumina

Do you have reason to believe the developers plan to abandon it?

Second, thanks very much for the heads-up on the contact form.  It has been corrected.
