### ISSUE TITLE
Not an Issue

### ISSUE THREAD

**Issue by halfagascan** [outpaddling/desktop-installer#23]
No issues with your  script.
Just some kudos on a job well done.
First time freebsd user and your script helped immensely, saved a lot of time and effort to give freebsd a try.
I first used this to install KDE5 on a desktop, complete in about an hour or so.
Second install was used to install kodi to a second drive, that will be used to view movies and tv, no issues at all with your script, however, kodi failed to start, lots of missing dependencies, filed a bug on that.
On the kodi install, first run thru, I chose  1.. No desktop software, thinking I would be able to select multimedia/kodi, no luck, so
on second run, I selected 15. Custom, that enabled me to select kodi and install, after installing the missing files, up pops kodi.
In reading over the script, I see no mention or description of the category "Other", maybe a blurb about its capabilities?
Thanks for taking the time to create a very helpful and straight forward script, that does what its meant to do.

**Comment by outpaddling** [comment]
Greatly appreciate the positive feedback and suggestions.
I just updated the Quick Start tab at http://acadix.biz/desktop-installer.php and the miserably outdated man page.
I will also mention kodi in the docs or maybe even support it explicitly in a future version.  Was not even aware of it until you mentioned it.
