### ISSUE TITLE
Feature request: Add VNC virtual desktop environment

### ISSUE THREAD

**Issue by rmx-it** [outpaddling/desktop-installer#25]
Hi,
for portable SOC's like RPI4 or Rock64 a virtual desktop environment would be quite handy.
While for RPI4 a normal graphical output is supported Rock64 is lacking graphical support.
A VNC virtual desktop environment could fill the gap and be user for graphical only tools via VNC.

desktop-installer should ask for a virtual screen resolution, install a VNC server and start it.
Maybe in conjunction with an WLAN AP....
All HW related drivers and settings could mostly be skipped (Maybe network, sound and KBD language settings remain)

BTW: Many thanks for your efforts!

**Comment by outpaddling** [comment]
Interesting idea...
This is honestly beyond the scope of what I would incorporate into desktop-installer proper.  I want to keep the script as simple and reliable as possible, focused on basic needs of most users.
This is fairly complicated and likely to be troublesome based on my experience with VNC.
However, I would be open to developing a "plugin" interface for external scripts to make things like this work smoothly.  If you can provide a script that performs the VNC server setup, we can figure out how to make desktop-installer utilize it as seamlessly as possible.

**Comment by outpaddling** [comment]
Closing for lack of feedback.  Please reopen if you still want to pursue this.
