### ISSUE TITLE
AMD, GDM, GNOME: FreeBSD bugs 253746 and 257810

### ISSUE THREAD

**Issue by grahamperrin** [outpaddling/desktop-installer#27]
Under <https://old.reddit.com/r/freebsd/comments/xpmn0z/> I mention FreeBSD bugs: 

* [253746 – x11-wm/mutter: Freezes on AMD GPU's with DRI3](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=253746)
* [257810 – x11/gnome3(-lite) & x11/gdm lags significantly on amdgpu](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=257810)

The first answer there suggested desktop-installer. I wonder, does the script alert the end user if there's the aim to use GNOME with AMD graphics?

**Comment by outpaddling** [comment]
No, I don't want to get into the business of chasing individual bugs in underlying software.
What I could potentially do is enhance the general warnings in auto-gpu-setup to educate users about possibilities like this one.  I'll give some thought to how it should be presented.

**Comment by outpaddling** [comment]
I made some small improvements to the text and committed sysutils/auto-admin so they will appear in the next branch.  We can make further improvements if you have any ideas.
