### ISSUE TITLE
Unnecessary pkg repository updates at every call

### ISSUE THREAD

**Issue by Defenso-QTH** [outpaddling/desktop-installer#45]
desktop-installer calls `pkg install` a fow dozen times during the process.

On every call, pkg checks for repository updates, although it already does it once at the beginning.

Having pkg skip this step would save some time on the whole process.

**Comment by outpaddling** [comment]
Added to the latest WIP port, available here:

[https://github.com/outpaddling/freebsd-ports-wip](https://github.com/outpaddling/freebsd-ports-wip)

Thanks for the suggestion!
