### ISSUE TITLE
HAL is retired

### ISSUE THREAD

**Issue by grahamperrin** [outpaddling/desktop-installer#9]
Hi

Background: https://old.reddit.com/r/freebsd/comments/ljjq4u/-/

https://www.freshports.org/sysutils/desktop-installer/#description mentions HAL; https://cgit.freebsd.org/ports/tree/sysutils/desktop-installer/pkg-descr?id=4069540498a7f54b980796950336d24e24b328c2#n3

https://github.com/outpaddling/desktop-installer/blob/bd13aed6694970ea04d92e04f5f7ec6cebaf00ae/desktop-installer#L221

https://github.com/outpaddling/desktop-installer/blob/5e85859774d5a2d0429ccd2b14c3b756c43a4351/Data/90-vboxguest.fdi#L4

**Comment by outpaddling** [comment]
Thanks for the heads-up.  I've been wanting to purge HAL references for years, but last time I checked it was still required for a couple things.
I just committed the HAL-free 0.7.2 to the ports tree.  New binary package should be generated withing a few days (for amd64 at least).
